# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GuiDraft.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, sip
from PyQt5.QtWidgets import QStackedLayout

class Ui_MainWindow(object):



    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(698, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(520, 510, 113, 32))
        self.start_button.setObjectName("start_button")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 10, 591, 201))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(20, 20, 60, 16))
        self.label_7.setObjectName("label_7")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(350, 160, 241, 42))
        self.widget.setObjectName("widget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.widget_2 = QtWidgets.QWidget(self.frame)
        self.widget_2.setGeometry(QtCore.QRect(0, 80, 241, 42))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.label_8 = QtWidgets.QLabel(self.widget_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.label_11 = QtWidgets.QLabel(self.widget_2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)



        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(30, 280, 581, 221))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")



        self.widget_4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_4.setGeometry(QtCore.QRect(90, 490, 120, 80))
        self.widget_4.setObjectName("widget_4")
        self.widget_4.show()

        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(20, 210, 221, 41))
        self.widget_3.setObjectName("widget_3")
        self.drop_down_menu = QtWidgets.QComboBox(self.widget_3)
        self.drop_down_menu.setGeometry(QtCore.QRect(10, 20, 184, 26))
        self.drop_down_menu.setObjectName("drop_down_menu")
        self.drop_down_menu.addItem("")
        self.drop_down_menu.addItem("")
        self.drop_down_menu.addItem("")
        self.drop_down_menu.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 698, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)


        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        #layout frames
        self.mainlayout = QStackedLayout()
        self.mainlayout2 = QStackedLayout()



        self.layoutWidgetFreeRun = QtWidgets.QWidget(self.frame_2)
        self.layoutWidgetFreeRunBlank1 = QtWidgets.QWidget(self.frame_2)

        self.layoutWidgetAlphaEye1 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidgetAlphaEye2 = QtWidgets.QWidget(self.frame_2)

        self.layoutWidgetASSR1 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidgetASSR2 = QtWidgets.QWidget(self.frame_2)




        self.free_run()
        self.alpha_or_eye_blink()
        self.ASSR()


        self.mainlayout.addWidget(self.layoutWidgetFreeRun)
        self.mainlayout.addWidget(self.layoutWidgetAlphaEye1)
        self.mainlayout.addWidget(self.layoutWidgetAlphaEye1)
        self.mainlayout.addWidget(self.layoutWidgetASSR1)

        self.mainlayout2.addWidget(self.layoutWidgetFreeRunBlank1)
        self.mainlayout2.addWidget(self.layoutWidgetAlphaEye2)
        self.mainlayout2.addWidget(self.layoutWidgetAlphaEye2)
        self.mainlayout2.addWidget(self.layoutWidgetASSR2)


        self.retranslateUi(MainWindow)

        self.drop_down_menu.activated['int'].connect(self.frameChange)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)




    def free_run(self):

        self.layoutWidgetFreeRun = QtWidgets.QWidget(self.frame_2)
        self.layoutWidgetFreeRun.setGeometry(QtCore.QRect(50, -10, 211, 87))
        self.layoutWidgetFreeRun.setObjectName("layoutWidgetFreeRun")


        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidgetFreeRun)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.start_delay_text = QtWidgets.QLabel(self.layoutWidgetFreeRun)
        self.start_delay_text.setObjectName("start_delay_text")
        self.start_delay_text.setText("Start Delay")

        self.horizontalLayout.addWidget(self.start_delay_text)

        self.start_delay_lineEdit= QtWidgets.QLineEdit(self.layoutWidgetFreeRun)
        self.start_delay_lineEdit.setObjectName("start_delay_lineEdit")

        self.horizontalLayout.addWidget(self.start_delay_lineEdit)

        self.verticalLayout.addLayout(self.horizontalLayout)


    def alpha_or_eye_blink(self):

        self.layoutWidgetAlphaEye1 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidgetAlphaEye1.setGeometry(QtCore.QRect(300, 20, 225, 84))
        self.layoutWidgetAlphaEye1.setObjectName("layoutWidgetAlphaEye1")


        self.verticalLayout_Right = QtWidgets.QVBoxLayout(self.layoutWidgetAlphaEye1)
        self.verticalLayout_Right.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_Right.setObjectName("verticalLayout_Right")


        self.horizontalLayoutRightTop = QtWidgets.QHBoxLayout()
        self.horizontalLayoutRightTop.setObjectName("horizontalLayoutRightTop")

        self.verticalLayout_Right1 = QtWidgets.QVBoxLayout()
        self.verticalLayout_Right1.setObjectName("verticalLayout_Right1")

        self.end_delay_text = QtWidgets.QLabel(self.layoutWidgetAlphaEye1)
        self.end_delay_text.setObjectName("end_delay_text")
        self.end_delay_text.setText("End Delay")


        self.verticalLayout_Right1.addWidget(self.end_delay_text)

        self.rest_length_text = QtWidgets.QLabel(self.layoutWidgetAlphaEye1)
        self.rest_length_text.setObjectName("rest_length_text")
        self.rest_length_text.setText("Rest Length")


        self.verticalLayout_Right1.addWidget(self.rest_length_text)

        self.horizontalLayoutRightTop.addLayout(self.verticalLayout_Right1)

        self.verticalLayout_Right2= QtWidgets.QVBoxLayout()
        self.verticalLayout_Right2.setObjectName("verticalLayout_Right2")

        self.end_delay_lineEdit = QtWidgets.QLineEdit(self.layoutWidgetAlphaEye1)
        self.end_delay_lineEdit.setObjectName("end_delay_lineEdit")


        self.verticalLayout_Right2.addWidget(self.end_delay_lineEdit)

        self.rest_length_lineEdit = QtWidgets.QLineEdit(self.layoutWidgetAlphaEye1)
        self.rest_length_lineEdit.setObjectName("rest_length_lineEdit")


        self.verticalLayout_Right2.addWidget(self.rest_length_lineEdit)

        self.horizontalLayoutRightTop.addLayout(self.verticalLayout_Right2)

        self.verticalLayout_Right.addLayout(self.horizontalLayoutRightTop)

        self.cue_audio_text = QtWidgets.QCheckBox(self.layoutWidgetAlphaEye1)
        self.cue_audio_text.setObjectName("cue_audio_text")
        self.cue_audio_text.setText("Cue Audio")


        self.verticalLayout_Right.addWidget(self.cue_audio_text)

        self.layoutWidgetAlphaEye2 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidgetAlphaEye2.setGeometry(QtCore.QRect(50, 20, 211, 87))
        self.layoutWidgetAlphaEye2.setObjectName("layoutWidgetAlphaEye2")


        self.horizontalLayoutLeft = QtWidgets.QHBoxLayout(self.layoutWidgetAlphaEye2)
        self.horizontalLayoutLeft.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayoutLeft.setObjectName("horizontalLayoutLeft")

        self.verticalLayoutLeft1 = QtWidgets.QVBoxLayout()
        self.verticalLayoutLeft1.setObjectName("verticalLayoutLeft1")

        self.start_delay_text = QtWidgets.QLabel(self.layoutWidgetAlphaEye2)
        self.start_delay_text.setObjectName("start_delay_text")
        self.start_delay_text.setText("Start Delay")


        self.verticalLayoutLeft1.addWidget(self.start_delay_text)

        self.cue_length_text = QtWidgets.QLabel(self.layoutWidgetAlphaEye2)
        self.cue_length_text.setObjectName("cue_length_text")
        self.cue_length_text.setText("Cue Length")


        self.verticalLayoutLeft1.addWidget(self.cue_length_text)

        self.repetitions_text = QtWidgets.QLabel(self.layoutWidgetAlphaEye2)
        self.repetitions_text.setObjectName("repetitions_text")
        self.repetitions_text.setText("Repetitions")


        self.verticalLayoutLeft1.addWidget(self.repetitions_text)

        self.horizontalLayoutLeft.addLayout(self.verticalLayoutLeft1)

        self.verticalLayoutLeft2 = QtWidgets.QVBoxLayout()
        self.verticalLayoutLeft2.setObjectName("verticalLayoutLeft2")

        self.start_delay_lineEdit = QtWidgets.QLineEdit(self.layoutWidgetAlphaEye2)
        self.start_delay_lineEdit.setObjectName("start_delay_lineEdit")


        self.verticalLayoutLeft2.addWidget(self.start_delay_lineEdit)

        self.cue_length_lineEdit = QtWidgets.QLineEdit(self.layoutWidgetAlphaEye2)
        self.cue_length_lineEdit.setObjectName("cue_length_lineEdit")


        self.verticalLayoutLeft2.addWidget(self.cue_length_lineEdit)

        self.repetitions_lineEdit = QtWidgets.QLineEdit(self.layoutWidgetAlphaEye2)
        self.repetitions_lineEdit.setObjectName("repetitions_lineEdit")


        self.verticalLayoutLeft2.addWidget(self.repetitions_lineEdit)

        self.horizontalLayoutLeft.addLayout(self.verticalLayoutLeft2)


    def ASSR(self):

        self.layoutWidgetASSR1 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidgetASSR1.setGeometry(QtCore.QRect(300, 20, 225, 140)) #84 --> 140
        self.layoutWidgetASSR1.setObjectName("layoutWidgetASSR1")
        self.layoutWidgetASSR1.show()


        self.verticalLayoutRight = QtWidgets.QVBoxLayout(self.layoutWidgetASSR1)
        self.verticalLayoutRight.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutRight.setObjectName("verticalLayoutRight")


        self.horizontalLayoutRightTop = QtWidgets.QHBoxLayout()
        self.horizontalLayoutRightTop.setObjectName("horizontalLayoutRightTop")

        self.verticalLayoutRight1 = QtWidgets.QVBoxLayout()
        self.verticalLayoutRight1.setObjectName("verticalLayoutRight1")

        self.end_delay_text = QtWidgets.QLabel(self.layoutWidgetASSR1)
        self.end_delay_text.setObjectName("end_delay_text")
        self.end_delay_text.setText("End Delay")


        self.verticalLayoutRight1.addWidget(self.end_delay_text)

        self.rest_length_text = QtWidgets.QLabel(self.layoutWidgetASSR1)
        self.rest_length_text.setObjectName("rest_length_text")
        self.rest_length_text.setText("Rest Length")


        self.verticalLayoutRight1.addWidget(self.rest_length_text)

        self.carrier_frequency_text = QtWidgets.QLabel(self.layoutWidgetASSR1)
        self.carrier_frequency_text.setObjectName("carrier_frequency_text")
        self.carrier_frequency_text.setText("Carrier Frequency")


        self.verticalLayoutRight1.addWidget(self.carrier_frequency_text)

        self.amplitude_modulation_frequency_text = QtWidgets.QLabel(self.layoutWidgetASSR1)
        self.amplitude_modulation_frequency_text.setObjectName("amplitude_modulation_frequency_text")
        self.amplitude_modulation_frequency_text.setText("Amp. Frequency")

        self.amplitude_modulation_frequency_text.setWordWrap(True)

        self.verticalLayoutRight1.addWidget(self.amplitude_modulation_frequency_text)

        self.horizontalLayoutRightTop.addLayout(self.verticalLayoutRight1)

        self.verticalLayoutRight2 = QtWidgets.QVBoxLayout()
        self.verticalLayoutRight2.setObjectName("verticalLayoutRight2")

        self.end_delay_lineEdit = QtWidgets.QLineEdit(self.layoutWidgetASSR1)
        self.end_delay_lineEdit.setObjectName("end_delay_lineEdit")


        self.verticalLayoutRight2.addWidget(self.end_delay_lineEdit)

        self.rest_length_lineEdit = QtWidgets.QLineEdit(self.layoutWidgetASSR1)
        self.rest_length_lineEdit.setObjectName("rest_length_lineEdit")

        self.verticalLayoutRight2.addWidget(self.rest_length_lineEdit)

        self.carrier_frequency_lineEdit = QtWidgets.QLineEdit(self.layoutWidgetASSR1)
        self.carrier_frequency_lineEdit.setObjectName("carrier_frequency_lineEdit")

        self.verticalLayoutRight2.addWidget(self.carrier_frequency_lineEdit)

        self.amplitude_modulation_frequency_lineEdit = QtWidgets.QLineEdit(self.layoutWidgetASSR1)
        self.amplitude_modulation_frequency_lineEdit.setObjectName("amplitude_modulation_frequency_lineEdit")

        self.verticalLayoutRight2.addWidget(self.amplitude_modulation_frequency_lineEdit)

        self.horizontalLayoutRightTop.addLayout(self.verticalLayoutRight2)

        self.verticalLayoutRight.addLayout(self.horizontalLayoutRightTop)

        self.cue_audio_text = QtWidgets.QCheckBox(self.layoutWidgetASSR1)
        self.cue_audio_text.setObjectName("cue_audio_text")
        self.cue_audio_text.setText("Cue Audio")

        self.verticalLayoutRight.addWidget(self.cue_audio_text)

        self.layoutWidgetASSR2 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidgetASSR2.setGeometry(QtCore.QRect(50, 20, 211, 115))
        self.layoutWidgetASSR2.setObjectName("layoutWidgetASSR2")


        self.horizontalLayoutLeft = QtWidgets.QHBoxLayout(self.layoutWidgetASSR2)
        self.horizontalLayoutLeft.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayoutLeft.setObjectName("horizontalLayoutLeft")

        self.verticalLayoutLeft1 = QtWidgets.QVBoxLayout()
        self.verticalLayoutLeft1.setObjectName("verticalLayout")

        self.start_delay_text = QtWidgets.QLabel(self.layoutWidgetASSR2)
        self.start_delay_text.setObjectName("start_delay_text")
        self.start_delay_text.setText("Start Delay")


        self.verticalLayoutLeft1.addWidget(self.start_delay_text)

        self.cue_length_text = QtWidgets.QLabel(self.layoutWidgetASSR2)
        self.cue_length_text.setObjectName("cue_length_text")
        self.cue_length_text.setText("Cue Length")


        self.verticalLayoutLeft1.addWidget(self.cue_length_text)

        self.repetitions_text = QtWidgets.QLabel(self.layoutWidgetASSR2)
        self.repetitions_text.setObjectName("repetitions_text")
        self.repetitions_text.setText("Repetitions")


        self.verticalLayoutLeft1.addWidget(self.repetitions_text)

        self.click_frequency_text = QtWidgets.QLabel(self.layoutWidgetASSR2)
        self.click_frequency_text.setObjectName("click_frequency_text")
        self.click_frequency_text.setText("Click Frequency")

        self.verticalLayoutLeft1.addWidget(self.click_frequency_text)

        self.horizontalLayoutLeft.addLayout(self.verticalLayoutLeft1)

        self.verticalLayoutLeft2 = QtWidgets.QVBoxLayout()
        self.verticalLayoutLeft2.setObjectName("verticalLayoutLeft2")

        self.start_delay_lineEdit = QtWidgets.QLineEdit(self.layoutWidgetASSR2)
        self.start_delay_lineEdit.setObjectName("start_delay_lineEdit")


        self.verticalLayoutLeft2.addWidget(self.start_delay_lineEdit)

        self.cue_length_lineEdit = QtWidgets.QLineEdit(self.layoutWidgetASSR2)
        self.cue_length_lineEdit.setObjectName("cue_length_lineEdit")


        self.verticalLayoutLeft2.addWidget(self.cue_length_lineEdit)

        self.repetitions_lineEdit = QtWidgets.QLineEdit(self.layoutWidgetASSR2)
        self.repetitions_lineEdit.setObjectName("repetitions_lineEdit")

        self.verticalLayoutLeft2.addWidget(self.repetitions_lineEdit)

        self.click_frequency_lineEdit = QtWidgets.QLineEdit(self.layoutWidgetASSR2)
        self.click_frequency_lineEdit.setObjectName("click_frequency_lineEdit")

        self.verticalLayoutLeft2.addWidget(self.click_frequency_lineEdit)

        self.horizontalLayoutLeft.addLayout(self.verticalLayoutLeft2)


    def frameChange(self, i):

        self.mainlayout.setCurrentIndex(i)
        self.mainlayout2.setCurrentIndex(i)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.start_button.setText(_translate("MainWindow", "Start"))
        self.label_7.setText(_translate("MainWindow", "Prompt"))
        self.label_9.setText(_translate("MainWindow", "Total Run Time"))
        self.label_10.setText(_translate("MainWindow", "TextLabel"))
        self.label_8.setText(_translate("MainWindow", "Cue Countdown"))
        self.label_11.setText(_translate("MainWindow", "TextLabel"))
        self.drop_down_menu.setItemText(0, _translate("MainWindow", "Free Run"))
        self.drop_down_menu.setItemText(1, _translate("MainWindow", "Eye Blinks"))
        self.drop_down_menu.setItemText(2, _translate("MainWindow", "Alpha"))
        self.drop_down_menu.setItemText(3, _translate("MainWindow", "ASSR"))
