# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GuiDraft.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, sip
from PyQt5.QtWidgets import QStackedLayout

class Ui_MainWindow(object):



    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(698, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(520, 510, 113, 32))
        self.start_button.setObjectName("start_button")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 10, 591, 201))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(20, 20, 60, 16))
        self.label_7.setObjectName("label_7")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(350, 160, 241, 42))
        self.widget.setObjectName("widget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.widget_2 = QtWidgets.QWidget(self.frame)
        self.widget_2.setGeometry(QtCore.QRect(0, 80, 241, 42))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.label_8 = QtWidgets.QLabel(self.widget_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.label_11 = QtWidgets.QLabel(self.widget_2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)



        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(30, 280, 581, 221))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")

        #self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        #self.frame_3.setGeometry(QtCore.QRect(30, 280, 581, 221))
        #self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        #self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        #self.frame_3.setObjectName("frame_3")

        #self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        #self.frame_4.setGeometry(QtCore.QRect(30, 280, 581, 221))
        #self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        #self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        #self.frame_4.setObjectName("frame_4")



        self.widget_4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_4.setGeometry(QtCore.QRect(90, 490, 120, 80))
        self.widget_4.setObjectName("widget_4")
        self.widget_4.show()

        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(20, 210, 221, 41))
        self.widget_3.setObjectName("widget_3")
        self.drop_down_menu = QtWidgets.QComboBox(self.widget_3)
        self.drop_down_menu.setGeometry(QtCore.QRect(10, 20, 184, 26))
        self.drop_down_menu.setObjectName("drop_down_menu")
        self.drop_down_menu.addItem("")
        self.drop_down_menu.addItem("")
        self.drop_down_menu.addItem("")
        self.drop_down_menu.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 698, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)


        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        #layout frames
        self.mainlayout = QStackedLayout()
        self.mainlayout2 = QStackedLayout()
        self.mainlayout3 = QStackedLayout()


        self.layoutWidgetX1 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidgetX2 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidgetX3 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidgetY1 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidgetY2 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidgetY3 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidgetZ1 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidgetZ2 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidgetZ3 = QtWidgets.QWidget(self.frame_2)



        self.free_run()
        self.alpha_or_eye_blink()
        self.ASSR()


        self.mainlayout.addWidget(self.layoutWidgetX1)
        self.mainlayout.addWidget(self.layoutWidgetY1)
        self.mainlayout.addWidget(self.layoutWidgetY1)
        self.mainlayout.addWidget(self.layoutWidgetZ1)

        self.mainlayout2.addWidget(self.layoutWidgetX2)
        self.mainlayout2.addWidget(self.layoutWidgetY2)
        self.mainlayout2.addWidget(self.layoutWidgetY2)
        self.mainlayout2.addWidget(self.layoutWidgetZ2)

        self.mainlayout3.addWidget(self.layoutWidgetX3)
        self.mainlayout3.addWidget(self.layoutWidgetY3)
        self.mainlayout3.addWidget(self.layoutWidgetY3)
        self.mainlayout3.addWidget(self.layoutWidgetZ3)


        #self.layoutWidget = QtWidgets.QWidget(self.frame_2)
        #self.layoutWidget.setGeometry(QtCore.QRect(50, -10, 211, 87))
        #self.layoutWidget.setObjectName("layoutWidget")

        #self.layoutWidget1 = QtWidgets.QWidget(self.frame_2)
        #self.layoutWidget1.setGeometry(QtCore.QRect(50, 20, 211, 87))
        #self.layoutWidget1.setObjectName("layoutWidget1")

        #self.layoutWidget3 = QtWidgets.QWidget(self.frame_2)
        #self.layoutWidget3.setGeometry(QtCore.QRect(50, 20, 211, 220))
        #self.layoutWidget3.setObjectName("layoutWidget3")

        #self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget)
        #self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        #self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        #self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        #self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        #self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        #self.verticalLayout = QtWidgets.QVBoxLayout()
        #self.verticalLayout_2 = QtWidgets.QVBoxLayout()


        #self.QtStack = QtWidgets.QStackedLayout()

        #self.stack1 = QtWidgets.QWidget()
        #self.stack2 = QtWidgets.QWidget()
        #self.stack3 = QtWidgets.QWidget()


        #self.free_run()
        #self.alpha_or_eye_blink()
        #self.ASSR()



        #self.QtStack.addWidget(self.stack1)
        #self.QtStack.addWidget(self.stack2)
        #self.QtStack.addWidget(self.stack3)



        self.retranslateUi(MainWindow)
        #self.drop_down_menu.currentIndexChanged().connect(self.clear)
        self.drop_down_menu.activated['int'].connect(self.frameChange)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    #def deleteLayout(self, layout):
    #    if layout is not None:
        #    while layout.count():
            #    item = layout.takeAt(0)
            #    widget = item.widget()
            #    if widget is not None:
            #        widget.deleteLater()
            #    else:
            #        self.deleteLayout(item.layout())
            #sip.delete(layout)

    #def clearlayouts(self):
        #for i in reversed(range(self.verticalLayout_5.count())):
        #    self.verticalLayout_5.itemAt(i).widget().deleteLater()
        #for i in reversed(range(self.horizontalLayout_10.count())):
    #        self.horizontalLayout_10.itemAt(i).widget().deleteLater()
    #    for i in reversed(range(self.horizontalLayout.count())):
    #        self.horizontalLayout.itemAt(i).widget().deleteLater()
    #    for i in reversed(range(self.horizontalLayout_3.count())):
    #        self.horizontalLayout_3.itemAt(i).widget().deleteLater()
    #    for i in reversed(range(self.verticalLayout_3.count())):
    #        self.verticalLayout_3.itemAt(i).widget().deleteLater()
    #    for i in reversed(range(self.verticalLayout_4.count())):
    #        self.verticalLayout_4.itemAt(i).widget().deleteLater()
    #    for i in reversed(range(self.verticalLayout.count())):
    #        self.verticalLayout.itemAt(i).widget().deleteLater()
    #    for i in reversed(range(self.verticalLayout_2.count())):
        #    self.verticalLayout_2.itemAt(i).widget().deleteLater()


    def free_run(self):


        #self.clearlayouts()
        #self.layoutWidget = QtWidgets.QWidget(self.frame_2)



        self.layoutWidgetX1 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidgetX1.setGeometry(QtCore.QRect(50, -10, 211, 87))
        self.layoutWidgetX1.setObjectName("layoutWidgetX1")



        #self.layoutWidget.setParent(None)
        #self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 0, 0))
        #self.layoutWidget1.setObjectName("layoutWidget1")

        #self.layoutWidget3.setGeometry(QtCore.QRect(0, 0, 0, 0))
        #self.layoutWidget3.setObjectName("layoutWidget3")

        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidgetX1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")

        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.start_delay_text = QtWidgets.QLabel(self.layoutWidgetX1)
        self.start_delay_text.setObjectName("start_delay_text")
        self.start_delay_text.setText("Start Delay")

        self.horizontalLayout.addWidget(self.start_delay_text)

        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidgetX1)
        self.lineEdit_4.setObjectName("lineEdit_4")

        self.horizontalLayout.addWidget(self.lineEdit_4)

        self.verticalLayout_5.addLayout(self.horizontalLayout)



        #self.stack1.setLayout(self.layoutWidget)
        #self.layoutWidgetX.show()

        #self.layoutWidget3.show()





    def alpha_or_eye_blink(self):

        #self.clearlayouts()


        self.layoutWidgetY1 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidgetY1.setGeometry(QtCore.QRect(300, 20, 225, 84))
        self.layoutWidgetY1.setObjectName("layoutWidgetY1")

        #self.layoutWidget3.setGeometry(QtCore.QRect(0, 0, 0, 0))
        #self.layoutWidget3.setObjectName("layoutWidget3")


        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidgetY1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")


        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.end_delay_text = QtWidgets.QLabel(self.layoutWidgetY1)
        self.end_delay_text.setObjectName("end_delay_text")
        self.end_delay_text.setText("End Delay")


        self.verticalLayout_3.addWidget(self.end_delay_text)

        self.rest_length_text = QtWidgets.QLabel(self.layoutWidgetY1)
        self.rest_length_text.setObjectName("rest_length_text")
        self.rest_length_text.setText("Rest Length")


        self.verticalLayout_3.addWidget(self.rest_length_text)

        self.horizontalLayout_3.addLayout(self.verticalLayout_3)

        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")

        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidgetY1)
        self.lineEdit_4.setObjectName("lineEdit_4")
        #self.lineEdit_4.show()

        self.verticalLayout_4.addWidget(self.lineEdit_4)

        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidgetY1)
        self.lineEdit_5.setObjectName("lineEdit_5")
        #self.lineEdit_5.show()

        self.verticalLayout_4.addWidget(self.lineEdit_5)

        self.horizontalLayout_3.addLayout(self.verticalLayout_4)

        self.verticalLayout_5.addLayout(self.horizontalLayout_3)

        self.cue_audio_text = QtWidgets.QCheckBox(self.layoutWidgetY1)
        self.cue_audio_text.setObjectName("cue_audio_text")
        self.cue_audio_text.setText("Cue Audio")


        self.verticalLayout_5.addWidget(self.cue_audio_text)

        self.layoutWidgetY2 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidgetY2.setGeometry(QtCore.QRect(50, 20, 211, 87))
        self.layoutWidgetY2.setObjectName("layoutWidgetY2")


        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidgetY2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")

        self.start_delay_text = QtWidgets.QLabel(self.layoutWidgetY2)
        self.start_delay_text.setObjectName("start_delay_text")
        self.start_delay_text.setText("Start Delay")


        self.verticalLayout.addWidget(self.start_delay_text)

        self.cue_length_text = QtWidgets.QLabel(self.layoutWidgetY2)
        self.cue_length_text.setObjectName("cue_length_text")
        self.cue_length_text.setText("Cue Length")


        self.verticalLayout.addWidget(self.cue_length_text)

        self.repetitions_text = QtWidgets.QLabel(self.layoutWidgetY2)
        self.repetitions_text.setObjectName("repetitions_text")
        self.repetitions_text.setText("Repetitions")


        self.verticalLayout.addWidget(self.repetitions_text)

        self.horizontalLayout.addLayout(self.verticalLayout)

        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidgetY2)
        self.lineEdit.setObjectName("lineEdit")
        #self.lineEdit.show()

        self.verticalLayout_2.addWidget(self.lineEdit)

        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidgetY2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        #self.lineEdit_2.show()

        self.verticalLayout_2.addWidget(self.lineEdit_2)

        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidgetY2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        #self.lineEdit_3.show()

        self.verticalLayout_2.addWidget(self.lineEdit_3)

        self.horizontalLayout.addLayout(self.verticalLayout_2)

        #self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        #self.layoutWidget2.setGeometry(QtCore.QRect(0, 0, 2, 2))
        #self.layoutWidget2.setObjectName("layoutWidget2")
        #self.layoutWidget2.show()

        #self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        #self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        #self.horizontalLayout_2.setObjectName("horizontalLayout_2")


        #self.layoutWidgetY.addWidget(self.layoutWidgetY1)
        #self.layoutWidgetY.addWidget(self.layoutWidgetY2)
        #self.layoutWidgetY1.show()
        #self.layoutWidget1.show()



        #self.layoutWidgetY1.setLayout(self.horizontalLayout)
        #self.layoutWidgetY2.setLayout(self.horizontalLayout)
        #self.stack2.setLayout(self.layoutWidget1)
        #self.layoutWidget3.show()

    def ASSR(self):



        self.layoutWidgetZ1 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidgetZ1.setGeometry(QtCore.QRect(300, 20, 225, 84))
        self.layoutWidgetZ1.setObjectName("layoutWidgetZ1")
        self.layoutWidgetZ1.show()


        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidgetZ1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")


        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.end_delay_text = QtWidgets.QLabel(self.layoutWidgetZ1)
        self.end_delay_text.setObjectName("end_delay_text")
        self.end_delay_text.setText("End Delay")


        self.verticalLayout_3.addWidget(self.end_delay_text)

        self.rest_length_text = QtWidgets.QLabel(self.layoutWidgetZ1)
        self.rest_length_text.setObjectName("rest_length_text")
        self.rest_length_text.setText("Rest Length")


        self.verticalLayout_3.addWidget(self.rest_length_text)

        self.horizontalLayout_3.addLayout(self.verticalLayout_3)

        self.verticalLayout_4 = QtWidgets.QVBoxLayout()

        self.verticalLayout_4.setObjectName("verticalLayout_4")

        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidgetZ1)
        self.lineEdit_4.setObjectName("lineEdit_4")
        #self.lineEdit_4.show()

        self.verticalLayout_4.addWidget(self.lineEdit_4)

        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidgetZ1)
        self.lineEdit_5.setObjectName("lineEdit_5")
        #self.lineEdit_5.show()

        self.verticalLayout_4.addWidget(self.lineEdit_5)

        self.horizontalLayout_3.addLayout(self.verticalLayout_4)

        self.verticalLayout_5.addLayout(self.horizontalLayout_3)

        self.cue_audio_text = QtWidgets.QCheckBox(self.layoutWidgetZ1)
        self.cue_audio_text.setObjectName("cue_audio_text")
        self.cue_audio_text.setText("Cue Audio")


        self.verticalLayout_5.addWidget(self.cue_audio_text)

        self.layoutWidgetZ2 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidgetZ2.setGeometry(QtCore.QRect(50, 20, 211, 115)) #87
        self.layoutWidgetZ2.setObjectName("layoutWidgetZ2")


        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidgetZ2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")

        self.start_delay_text = QtWidgets.QLabel(self.layoutWidgetZ2)
        self.start_delay_text.setObjectName("start_delay_text")
        self.start_delay_text.setText("Start Delay")


        self.verticalLayout.addWidget(self.start_delay_text)

        self.cue_length_text = QtWidgets.QLabel(self.layoutWidgetZ2)
        self.cue_length_text.setObjectName("cue_length_text")
        self.cue_length_text.setText("Cue Length")


        self.verticalLayout.addWidget(self.cue_length_text)

        self.repetitions_text = QtWidgets.QLabel(self.layoutWidgetZ2)
        self.repetitions_text.setObjectName("repetitions_text")
        self.repetitions_text.setText("Repetitions")


        self.verticalLayout.addWidget(self.repetitions_text)

        self.click_frequency_text = QtWidgets.QLabel(self.layoutWidgetZ2)
        self.click_frequency_text.setObjectName("click_frequency_text")
        self.click_frequency_text.setText("Click Frequency")

        self.verticalLayout.addWidget(self.click_frequency_text)

        self.horizontalLayout.addLayout(self.verticalLayout)

        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidgetZ2)
        self.lineEdit.setObjectName("lineEdit")
        #self.lineEdit.show()

        self.verticalLayout_2.addWidget(self.lineEdit)

        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidgetZ2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        #self.lineEdit_2.show()

        self.verticalLayout_2.addWidget(self.lineEdit_2)

        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidgetZ2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        #self.lineEdit_3.show()


        self.verticalLayout_2.addWidget(self.lineEdit_3)


        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidgetZ2)
        self.lineEdit_6.setObjectName("lineEdit")

        self.verticalLayout_2.addWidget(self.lineEdit_6)

        self.horizontalLayout.addLayout(self.verticalLayout_2)

        #self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        #self.layoutWidget2.setGeometry(QtCore.QRect(0, 0, 2, 2))
        #self.layoutWidget2.setObjectName("layoutWidget2")
        #self.layoutWidget2.show()


        self.layoutWidgetZ3 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidgetZ3.setGeometry(QtCore.QRect(50, 20, 211, 220))
        self.layoutWidgetZ3.setObjectName("layoutWidgetZ3")

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidgetZ3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)


        #self.layoutWidget.show()
        #self.layoutWidget1.show()
        #self.layoutWidget3.show()


        #self.stack2.setLayout(layoutWidget3)


    #def remove_homeScreen(self, layout):

        #for i in reversed(range(layout.count())):
            #item = layout.itemAt(i)

        #if isinstance(item, QtGui.QWidgetItem):

        #    item.widget().close()

        #else:
            #self.remove_homeScreen(item.layout())
#
    # remove the item from layout
        #layout.removeItem(item)

    # when select an option from drop down menu, clicking set does this
    # intakes integer
    def frameChange(self, i):

        #delete any previous frames before adding a new frame
        #for i in reversed(range(self.layoutWidget.count())):
        #    self.layoutWidget.itemAt(i).widget().setParent(None)
        #self.remove_homeScreen(self.layoutWidget)
        #self.remove_homeScreen(self.layoutWidget1)
        #self.remove_homeScreen(self.layoutWidget3)
        #for i in reversed(range(layout.count())):

        #self.setupUi(self)..setParent(None)

        #self.setupUi(self).layoutWidget1.setParent(None)
        #self.setupUi(self).layoutWidget3.setParent(None)

        #layout.itemAt(i).widget().deleteLater()
        #Free Run screen
#------------

        self.mainlayout.setCurrentIndex(i)
        self.mainlayout2.setCurrentIndex(i)
        #if i == 0:



        #    self.free_run()

                        #self.layoutWidget.setParent(None)
        #Eye Blink screen
        #elif i == 1:
                        #if layoutWidget.winfo_exists():
                            #    self.layoutWidget.deleteLater()
                        #if self.layoutWidget1.winfo_exists():
                            #self.layoutWidget1.deleteLater()


            #self.alpha_or_eye_blink()



        #Alpha screen
        #elif i == 2:
                #if self.layoutWidget.winfo_exists():
                #    self.layoutWidget.deleteLater()
                #if self.layoutWidget1.winfo_exists():
                #    self.layoutWidget1.deleteLater()


            #self.alpha_or_eye_blink()

        #ASSR screen
        #elif i == 3:
                #if self.layoutWidget.winfo_exists():
                #    self.layoutWidget.deleteLater()
                #if self.layoutWidget1.winfo_exists():
                #    self.layoutWidget1.deleteLater()

            #self.ASSR()








            #self.verticalLayout_3.addWidget(self.end_delay_text)
            #self.rest_length_text = QtWidgets.QLabel(self.layoutWidget)
            #self.rest_length_text.setObjectName("rest_length_text")
            #self.verticalLayout_3.addWidget(self.rest_length_text)
            #self.horizontalLayout_3.addLayout(self.verticalLayout_3)
            #self.verticalLayout_4 = QtWidgets.QVBoxLayout()
            #self.verticalLayout_4.setObjectName("verticalLayout_4")
            #self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget)
            #self.lineEdit_4.setObjectName("lineEdit_4")
            #self.verticalLayout_4.addWidget(self.lineEdit_4)
            #self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget)
            #self.lineEdit_5.setObjectName("lineEdit_5")
            #self.verticalLayout_4.addWidget(self.lineEdit_5)
            #self.horizontalLayout_3.addLayout(self.verticalLayout_4)
            #self.verticalLayout_5.addLayout(self.horizontalLayout_3)
            #self.cue_audio_text = QtWidgets.QCheckBox(self.layoutWidget)
            #self.cue_audio_text.setObjectName("cue_audio_text")
            #self.verticalLayout_5.addWidget(self.cue_audio_text)
            #self.layoutWidget1 = QtWidgets.QWidget(self.frame_2)
            #self.layoutWidget1.setGeometry(QtCore.QRect(50, 20, 211, 87))
            #self.layoutWidget1.setObjectName("layoutWidget1")
            #self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
            #self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
            #self.horizontalLayout.setObjectName("horizontalLayout")
            #self.verticalLayout = QtWidgets.QVBoxLayout()
            #self.verticalLayout.setObjectName("verticalLayout")
            #self.start_delay_text = QtWidgets.QLabel(self.layoutWidget1)
            #self.start_delay_text.setObjectName("start_delay_text")
            #self.verticalLayout.addWidget(self.start_delay_text)
            #self.cue_length_text = QtWidgets.QLabel(self.layoutWidget1)
            #self.cue_length_text.setObjectName("cue_length_text")
            #self.verticalLayout.addWidget(self.cue_length_text)
            #self.repetitions_text = QtWidgets.QLabel(self.layoutWidget1)
            #self.repetitions_text.setObjectName("repetitions_text")
            #self.verticalLayout.addWidget(self.repetitions_text)
            #self.horizontalLayout.addLayout(self.verticalLayout)
            #self.verticalLayout_2 = QtWidgets.QVBoxLayout()
            #self.verticalLayout_2.setObjectName("verticalLayout_2")
            #self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
            #self.lineEdit.setObjectName("lineEdit")
            #self.verticalLayout_2.addWidget(self.lineEdit)
            #self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget1)
            #self.lineEdit_2.setObjectName("lineEdit_2")
            #self.verticalLayout_2.addWidget(self.lineEdit_2)
            #self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget1)
            #self.lineEdit_3.setObjectName("lineEdit_3")
            #self.verticalLayout_2.addWidget(self.lineEdit_3)
            #self.horizontalLayout.addLayout(self.verticalLayout_2)
            #self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
            #self.layoutWidget2.setGeometry(QtCore.QRect(0, 0, 2, 2))
            #self.layoutWidget2.setObjectName("layoutWidget2")

            #self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
            #self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
            #self.horizontalLayout_2.setObjectName("horizontalLayout_2")





        #    print(hi)
        #elif i = 2:
        #elif i = 3:

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.start_button.setText(_translate("MainWindow", "Start"))
        self.label_7.setText(_translate("MainWindow", "Prompt"))
        self.label_9.setText(_translate("MainWindow", "Total Run Time"))
        self.label_10.setText(_translate("MainWindow", "TextLabel"))
        self.label_8.setText(_translate("MainWindow", "Cue Countdown"))
        self.label_11.setText(_translate("MainWindow", "TextLabel"))
        #self.end_delay_text.setText(_translate("MainWindow", "End Delay"))
        #self.rest_length_text.setText(_translate("MainWindow", "Rest Length"))
        #self.cue_audio_text.setText(_translate("MainWindow", "Cue Audio"))
        #self.start_delay_text.setText(_translate("MainWindow", "Start Delay"))
        #self.cue_length_text.setText(_translate("MainWindow", "Cue Length"))
        #self.repetitions_text.setText(_translate("MainWindow", "Repetitions"))
        self.drop_down_menu.setItemText(0, _translate("MainWindow", "Free Run"))
        self.drop_down_menu.setItemText(1, _translate("MainWindow", "Eye Blinks"))
        self.drop_down_menu.setItemText(2, _translate("MainWindow", "Alpha"))
        self.drop_down_menu.setItemText(3, _translate("MainWindow", "ASSR"))
